// Pre-generates ElevenLabs mp3s for every (voice × language × phrase) combo
// in src/game/i18n.ts and writes a manifest the runtime can consult before
// hitting the API.
//
// Usage: npm run voice-cache
//
// Reads VITE_ELEVENLABS_API_KEY from .env. Existing files are skipped (re-runs
// only generate missing combos), so it's safe to interrupt + resume. The
// voice list and phrase list are imported directly from the runtime modules,
// so they can't drift.
//
// To force-regenerate a specific phrase: delete its .mp3 from
// public/assets/voice/<voiceId>/<hash>.mp3 and re-run.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { getStrings, type Lang } from '../src/game/i18n.ts';
import { VOICE_CHARACTERS } from '../src/game/useFunnySpeech.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');

const envContent = readFileSync(join(ROOT, '.env'), 'utf-8');
const env = Object.fromEntries(
  envContent
    .split('\n')
    .filter((l) => l.trim() && !l.startsWith('#'))
    .map((l) => {
      const idx = l.indexOf('=');
      return [
        l.slice(0, idx).trim(),
        l.slice(idx + 1).trim().replace(/^["']|["']$/g, ''),
      ];
    }),
);

const API_KEY = env.VITE_ELEVENLABS_API_KEY;
if (!API_KEY) {
  console.error('VITE_ELEVENLABS_API_KEY not found in .env');
  process.exit(1);
}

const MODEL_ID = 'eleven_multilingual_v2';

// Distinct voice IDs across all languages. The same voice ID is reused across
// cs + en under different labels — dedupe so we don't generate twice.
const VOICES = Object.values(VOICE_CHARACTERS)
  .flat()
  .reduce<{ id: string; label: string }[]>((acc, v) => {
    if (acc.some((existing) => existing.id === v.voiceId)) return acc;
    acc.push({ id: v.voiceId, label: v.label });
    return acc;
  }, []);

function phrasesForLang(lang: Lang): string[] {
  const adult = getStrings(lang, false);
  const kid = getStrings(lang, true);

  const extract = (s: typeof adult) => {
    const multi = Object.values(s.multiTagPhrases).filter(
      (v): v is string => typeof v === 'string',
    );
    return [...multi, s.goalShout, ...s.tagPhrases];
  };

  const allPhrases = [...extract(adult), ...extract(kid)];
  return Array.from(new Set(allPhrases));
}

const PHRASES_BY_LANG: Record<Lang, string[]> = {
  cs: phrasesForLang('cs'),
  en: phrasesForLang('en'),
};

function hashKey(voiceId: string, lang: string, text: string) {
  return createHash('sha256')
    .update(`${voiceId}:${lang}:${text}`)
    .digest('hex')
    .slice(0, 16);
}

async function generateOne(voiceId: string, lang: Lang, text: string) {
  const hash = hashKey(voiceId, lang, text);
  const relPath = `voice/${voiceId}/${hash}.mp3`;
  const absPath = join(ROOT, 'public', 'assets', relPath);
  if (existsSync(absPath)) {
    return { relPath, skipped: true, chars: text.length };
  }
  const res = await fetch(
    `https://api.elevenlabs.io/v1/text-to-speech/${voiceId}?output_format=mp3_44100_128`,
    {
      method: 'POST',
      headers: {
        'xi-api-key': API_KEY,
        'Content-Type': 'application/json',
        Accept: 'audio/mpeg',
      },
      body: JSON.stringify({
        text,
        model_id: MODEL_ID,
        language_code: lang,
      }),
    },
  );
  if (!res.ok) {
    throw new Error(`ElevenLabs ${res.status}: ${await res.text()}`);
  }
  const buf = Buffer.from(await res.arrayBuffer());
  mkdirSync(dirname(absPath), { recursive: true });
  writeFileSync(absPath, buf);
  return { relPath, skipped: false, chars: text.length };
}

const manifest: Record<string, string> = {};
let totalChars = 0;
let generated = 0;
let skipped = 0;
let failed = 0;

for (const { id: voiceId, label } of VOICES) {
  for (const [lang, phrases] of Object.entries(PHRASES_BY_LANG) as Array<
    [Lang, string[]]
  >) {
    console.log(`\n--- ${label} (${voiceId}) [${lang}] ---`);
    for (const text of phrases) {
      const key = `${voiceId}:${lang}:${text}`;
      process.stdout.write(`  ${text} ... `);
      try {
        const result = await generateOne(voiceId, lang, text);
        manifest[key] = result.relPath;
        if (result.skipped) {
          skipped += 1;
          console.log('cached');
        } else {
          generated += 1;
          totalChars += result.chars;
          console.log(`ok (${result.chars} chars)`);
        }
        await new Promise((r) => setTimeout(r, 80));
      } catch (err) {
        failed += 1;
        console.log(`FAIL: ${(err as Error).message}`);
      }
    }
  }
}

const manifestTsPath = join(ROOT, 'src', 'game', 'voiceCacheManifest.ts');
const manifestTs = `// Auto-generated by scripts/generate-voice-cache.ts — do not edit by hand.
// Maps "\${voiceId}:\${lang}:\${text}" → static asset path under public/assets/.
export const VOICE_CACHE_MANIFEST: Readonly<Record<string, string>> = ${JSON.stringify(
  manifest,
  null,
  2,
)};
`;
writeFileSync(manifestTsPath, manifestTs);

console.log(`\n========================================`);
console.log(`Generated: ${generated} new files (${totalChars} characters)`);
console.log(`Skipped:   ${skipped} already-cached files`);
if (failed > 0) console.log(`Failed:    ${failed}`);
console.log(`Manifest:  ${manifestTsPath}`);
